<?php

use App\Controllers\Admin\DashboardController;
use App\Controllers\Admin\ThreadManageController;
use App\Controllers\Admin\PostManageController;
use App\Controllers\Admin\UserManageController;
use App\Controllers\Admin\ReviewController;
use App\Controllers\Admin\SectionManageController;
use App\Controllers\Admin\BannerController;
use App\Controllers\Admin\AnnouncementController;
use App\Controllers\Admin\RoleController;
use App\Controllers\Admin\UpdateCenterController;
use App\Controllers\Admin\SettingController;
use App\Controllers\Admin\MessageController;
use App\Controllers\Admin\ExtensionController;
use App\Controllers\Admin\FinanceController;
use App\Controllers\Admin\SocialController;
use App\Controllers\Admin\SystemCheckController;
use App\Controllers\Admin\ReportController;
use App\Controllers\Admin\VerificationController;
use App\Controllers\Admin\GrowthController;
use App\Controllers\Admin\LicenseController;
use App\Controllers\Admin\BadgeController;
use App\Controllers\Admin\AvatarFrameController;
use App\Controllers\Admin\BubbleController;
use App\Controllers\Admin\NameplateController;
use App\Controllers\Admin\AuditLogController;
use App\Controllers\Admin\RecycleBinController;
use App\Controllers\Admin\BackupController;
use App\Controllers\Admin\PaymentController;
use App\Controllers\Admin\BountyController;
use App\Controllers\Admin\UserCreditController;

$router->get('/admin', [DashboardController::class, 'index']);
$router->get('/admin/update-center', [UpdateCenterController::class, 'index']);
$router->post('/admin/update-center', [UpdateCenterController::class, 'index']);
$router->get('/admin/license', [LicenseController::class, 'index']);
$router->post('/admin/license', [LicenseController::class, 'index']);
$router->get('/admin/settings', [SettingController::class, 'index']);
$router->post('/admin/settings', [SettingController::class, 'index']);
$router->get('/admin/extensions', [ExtensionController::class, 'index']);
$router->post('/admin/extensions', [ExtensionController::class, 'index']);
$router->get('/admin/badges', [BadgeController::class, 'index']);
$router->post('/admin/badges', [BadgeController::class, 'index']);
$router->get('/admin/avatar-frames', [AvatarFrameController::class, 'index']);
$router->post('/admin/avatar-frames', [AvatarFrameController::class, 'index']);
$router->get('/admin/bubbles', [BubbleController::class, 'index']);
$router->post('/admin/bubbles', [BubbleController::class, 'index']);
$router->get('/admin/nameplates', [NameplateController::class, 'index']);
$router->post('/admin/nameplates', [NameplateController::class, 'index']);
$router->get('/admin/finance', [FinanceController::class, 'index']);
$router->get('/admin/bounties', [BountyController::class, 'index']);
$router->post('/admin/bounties', [BountyController::class, 'index']);
$router->get('/admin/payments', [PaymentController::class, 'index']);
$router->post('/admin/payments/channel', [PaymentController::class, 'channel']);
$router->post('/admin/payments/package', [PaymentController::class, 'package']);
$router->post('/admin/payments/package/delete', [PaymentController::class, 'deletePackage']);
$router->post('/admin/payments/order/paid', [PaymentController::class, 'markPaid']);
$router->post('/admin/payments/order/delete', [PaymentController::class, 'deleteOrder']);
$router->post('/admin/payments/redeem', [PaymentController::class, 'redeemCode']);
$router->post('/admin/payments/redeem/delete', [PaymentController::class, 'deleteRedeemCode']);
$router->post('/admin/finance/currency', [FinanceController::class, 'currency']);
$router->post('/admin/finance/currency/delete', [FinanceController::class, 'deleteCurrency']);
$router->post('/admin/finance/adjust', [FinanceController::class, 'adjust']);
$router->post('/admin/finance/reverse', [FinanceController::class, 'reverse']);
$router->get('/admin/system-check', [SystemCheckController::class, 'index']);
$router->get('/admin/backups', [BackupController::class, 'index']);
$router->post('/admin/backups', [BackupController::class, 'index']);
$router->get('/admin/audit-logs', [AuditLogController::class, 'index']);
$router->get('/admin/recycle-bin', [RecycleBinController::class, 'index']);
$router->post('/admin/recycle-bin', [RecycleBinController::class, 'index']);
$router->get('/admin/social', [SocialController::class, 'index']);
$router->get('/admin/verifications', [VerificationController::class, 'index']);
$router->get('/admin/tasks', [GrowthController::class, 'index']);
$router->post('/admin/tasks/task', [GrowthController::class, 'saveTask']);
$router->post('/admin/tasks/task/delete', [GrowthController::class, 'deleteTask']);
$router->post('/admin/tasks/submission/review', [GrowthController::class, 'reviewSubmission']);
$router->get('/admin/growth', [GrowthController::class, 'index']); 
$router->post('/admin/growth/checkin', [GrowthController::class, 'saveCheckin']);
$router->post('/admin/growth/level', [GrowthController::class, 'saveLevel']);
$router->post('/admin/growth/level/delete', [GrowthController::class, 'deleteLevel']);
$router->post('/admin/growth/adjust', [GrowthController::class, 'adjust']);
$router->post('/admin/growth/task', [GrowthController::class, 'saveTask']); 
$router->post('/admin/growth/task/delete', [GrowthController::class, 'deleteTask']); 
$router->post('/admin/growth/submission/review', [GrowthController::class, 'reviewSubmission']); 
$router->post('/admin/verifications/type', [VerificationController::class, 'saveType']);
$router->post('/admin/verifications/type/delete', [VerificationController::class, 'deleteType']);
$router->post('/admin/verifications/settings', [VerificationController::class, 'saveSettings']);
$router->post('/admin/verifications/review', [VerificationController::class, 'review']);
$router->post('/admin/verifications/revoke', [VerificationController::class, 'revoke']);
$router->post('/admin/social/delete', [SocialController::class, 'delete']);
$router->get('/admin/reports', [ReportController::class, 'index']);
$router->post('/admin/reports/handle', [ReportController::class, 'handle']);
$router->post('/admin/reports/target-action', [ReportController::class, 'targetAction']);


use App\Controllers\Admin\AdminGroupController;
$router->get('/admin/group-manage', [AdminGroupController::class, 'index']);
$router->get('/admin/group-manage/view', [AdminGroupController::class, 'view']);
$router->get('/admin/group-manage/report-view', [AdminGroupController::class, 'reportView']);
$router->post('/admin/group-manage/action', [AdminGroupController::class, 'action']);
$router->post('/admin/group-manage/process-report', [AdminGroupController::class, 'processReport']);
$router->get('/admin/threads', [ThreadManageController::class, 'index']);
$router->get('/admin/threads/edit', [ThreadManageController::class, 'edit']);
$router->post('/admin/threads/edit', [ThreadManageController::class, 'update']);
$router->post('/admin/threads/action', [ThreadManageController::class, 'action']);
$router->post('/admin/threads/bulk', [ThreadManageController::class, 'bulk']);
$router->get('/admin/posts', [PostManageController::class, 'index']);
$router->post('/admin/posts/action', [PostManageController::class, 'action']);
$router->get('/admin/posts/edit', [PostManageController::class, 'edit']);
$router->post('/admin/posts/edit', [PostManageController::class, 'update']);
$router->get('/admin/user-credit', [UserCreditController::class, 'index']);
$router->post('/admin/user-credit/settings', [UserCreditController::class, 'settings']);
$router->post('/admin/user-credit/adjust', [UserCreditController::class, 'adjust']);
$router->get('/admin/users', [UserManageController::class, 'index']);
$router->post('/admin/users/action', [UserManageController::class, 'action']);
$router->get('/admin/users/edit', [UserManageController::class, 'edit']);
$router->post('/admin/users/edit', [UserManageController::class, 'update']);
$router->post('/admin/users/delete', [UserManageController::class, 'delete']);
$router->get('/admin/review', [ReviewController::class, 'index']);
$router->get('/admin/moderator-workbench', [ReviewController::class, 'moderatorWorkbench']);
$router->get('/admin/reviewer-workbench', [ReviewController::class, 'reviewerWorkbench']);
$router->post('/admin/review/action', [ReviewController::class, 'action']);
$router->post('/admin/review/bulk', [ReviewController::class, 'bulkAction']);
$router->post('/admin/review/ai-recheck', [ReviewController::class, 'aiRecheck']);
$router->post('/admin/review/settings', [ReviewController::class, 'saveSettings']);
$router->post('/admin/review/provider', [ReviewController::class, 'saveProvider']);
$router->post('/admin/review/provider/delete', [ReviewController::class, 'deleteProvider']);
$router->post('/admin/review/provider/test', [ReviewController::class, 'testProvider']);
$router->get('/admin/sections', [SectionManageController::class, 'index']);
$router->post('/admin/sections', [SectionManageController::class, 'index']);
$router->post('/admin/sections/action', [SectionManageController::class, 'action']);
$router->get('/admin/banners', [BannerController::class, 'index']);
$router->post('/admin/banners', [BannerController::class, 'index']);
$router->get('/admin/announcements', [AnnouncementController::class, 'index']);
$router->post('/admin/announcements', [AnnouncementController::class, 'index']);
$router->get('/admin/roles', [RoleController::class, 'index']);
$router->post('/admin/roles', [RoleController::class, 'index']);
$router->get('/admin/roles/user', [RoleController::class, 'userRoles']);


$router->get('/admin/messages', [MessageController::class, 'index']);
$router->get('/admin/messages/create', [MessageController::class, 'create']);
$router->post('/admin/messages/create', [MessageController::class, 'create']);
$router->get('/admin/messages/edit', [MessageController::class, 'edit']);
$router->post('/admin/messages/edit', [MessageController::class, 'edit']);
$router->post('/admin/messages/delete', [MessageController::class, 'delete']);


use App\Controllers\Admin\AdminSoftwareController;
$router->get('/admin/software', [AdminSoftwareController::class, 'index']);
$router->post('/admin/software/review', [AdminSoftwareController::class, 'review']);
$router->post('/admin/software/version-review', [AdminSoftwareController::class, 'reviewVersion']);
$router->post('/admin/software/remove', [AdminSoftwareController::class, 'remove']);
$router->post('/admin/software/unpublish', [AdminSoftwareController::class, 'unpublish']);
$router->post('/admin/software/recommend', [AdminSoftwareController::class, 'setRecommended']);
$router->post('/admin/software/categories/save', [AdminSoftwareController::class, 'saveCategory']);
$router->post('/admin/software/categories/delete', [AdminSoftwareController::class, 'deleteCategory']);
$router->post('/admin/software/types/save', [AdminSoftwareController::class, 'saveType']);
$router->post('/admin/software/types/delete', [AdminSoftwareController::class, 'deleteType']);
$router->post('/admin/software/settings/save', [AdminSoftwareController::class, 'saveSettings']);
