<style>
body .topbar{position:fixed!important;top:0;left:0;right:0;z-index:10!important}.medal-page{min-height:100vh!important;background:linear-gradient(180deg,#f8fbff 0%,#f4f7fb 48%,#eef3fb 100%)!important;padding:0 16px 112px!important}.medal-page a{text-decoration:none!important}
.medal-hero{max-width:1180px!important;margin:0 auto 16px!important;display:flex!important;align-items:center!important;justify-content:space-between!important;gap:18px!important;background:linear-gradient(135deg,#0f172a,#1e3a8a 52%,#7c3aed)!important;color:#fff!important;border-radius:30px!important;padding:28px!important;box-shadow:0 24px 70px rgba(30,58,138,.26)!important;position:relative!important;overflow:visible!important}.medal-hero:after{content:"";position:absolute;right:-110px;top:-120px;width:360px;height:360px;border-radius:999px;background:radial-gradient(circle,rgba(255,255,255,.22),rgba(255,255,255,0) 66%)}.medal-kicker{display:inline-flex!important;font-size:12px!important;font-weight:900!important;letter-spacing:.16em!important;text-transform:uppercase!important;opacity:.86!important;margin-bottom:8px!important}.medal-hero h1{margin:0 0 8px!important;font-size:34px!important;letter-spacing:-.04em!important;line-height:1.08!important}.medal-hero p{margin:0!important;max-width:650px!important;color:rgba(255,255,255,.82)!important;line-height:1.75!important}.medal-hero-action{position:relative!important;z-index:1!important;display:inline-flex!important;align-items:center!important;justify-content:center!important;min-height:44px!important;padding:0 18px!important;border-radius:999px!important;background:#fff!important;color:#1d4ed8!important;font-weight:900!important;box-shadow:0 16px 34px rgba(15,23,42,.18)!important}
.medal-alert{max-width:1180px!important;margin:0 auto 12px!important;border-radius:16px!important;padding:12px 14px!important;font-weight:800!important}.medal-alert.error{background:#fef2f2!important;color:#991b1b!important;border:1px solid #fecaca!important}
.medal-shell{max-width:1180px!important;margin:0 auto!important;display:grid!important;gap:16px!important}
.medal-board{display:grid!important;grid-template-columns:minmax(0,1fr) 270px!important;gap:16px!important;align-items:stretch!important}
.medal-panel{background:rgba(255,255,255,.92)!important;border:1px solid rgba(226,232,240,.95)!important;border-radius:26px!important;padding:20px!important;box-shadow:0 16px 44px rgba(15,23,42,.06)!important;backdrop-filter:blur(12px)!important}.medal-panel-head{display:flex!important;align-items:flex-end!important;justify-content:space-between!important;gap:12px!important;margin-bottom:14px!important}.medal-panel h2{margin:0!important;font-size:20px!important;letter-spacing:-.035em!important}.medal-panel p{margin:5px 0 0!important;color:#64748b!important;font-size:13px!important;line-height:1.65!important}
.medal-slots-panel{position:relative!important}.medal-count{display:flex!important;align-items:center!important;gap:6px!important;font-size:12px!important;font-weight:900!important;color:#94a3b8!important;white-space:nowrap!important}.medal-count strong{font-size:20px!important;color:#0f172a!important;line-height:1!important}
.medal-slots{display:grid!important;grid-template-columns:repeat(5,1fr)!important;gap:10px!important}.medal-slot{min-height:108px!important;border:2px dashed #e2e8f0!important;border-radius:22px!important;background:#f8fafc!important;display:flex!important;flex-direction:column!important;align-items:center!important;justify-content:center!important;gap:8px!important;cursor:pointer!important;transition:border-color .16s ease,background .16s ease!important}.medal-slot.dragover,.medal-slot.is-over{border-color:#3b82f6!important;background:#eff6ff!important}.medal-slot img{width:48px!important;height:48px!important;object-fit:contain!important}.medal-slot small{font-size:11px!important;font-weight:900!important;color:#94a3b8!important}.medal-slot.active{border:2px solid var(--medal-color,#2563eb)!important;border-style:solid!important;background:color-mix(in srgb,var(--medal-color,#2563eb) 6%,#fff)!important}.slot-index{position:absolute!important;top:8px!important;left:10px!important;font-size:10px!important;font-weight:900!important;color:#94a3b8!important}.medal-slot{position:relative!important}.slot-medal{border:0!important;background:transparent!important;padding:0!important;cursor:grab!important}.slot-remove{position:absolute!important;top:6px!important;right:6px!important;border:0!important;background:rgba(0,0,0,.06)!important;border-radius:50%!important;width:20px!important;height:20px!important;display:flex!important;align-items:center!important;justify-content:center!important;cursor:pointer!important;opacity:.5!important}.slot-remove:hover{opacity:1!important;background:rgba(239,68,68,.1)!important}.slot-remove svg{width:12px!important;height:12px!important;color:#ef4444!important}.slot-empty{display:flex!important;flex-direction:column!important;align-items:center!important;gap:6px!important;color:#94a3b8!important;font-size:12px!important;font-weight:800!important}.slot-empty span{display:block!important;width:40px!important;height:40px!important;border-radius:14px!important;border:1px dashed #cbd5e1!important;background:#fff!important}
.medal-side-stats{padding:20px!important;display:grid!important;gap:12px!important;align-content:start!important}.side-stat{border-radius:20px!important;padding:14px!important;background:#fff!important;border:1px solid #e2e8f0!important}.side-stat strong{display:block!important;font-size:26px!important;letter-spacing:-.04em!important}.side-stat span{display:block!important;margin-top:5px!important;color:#64748b!important;font-size:12px!important;font-weight:900!important}
.medal-library{padding:18px!important}
.library-top{display:flex!important;align-items:center!important;justify-content:space-between!important;gap:12px!important;flex-wrap:wrap!important;margin-bottom:14px!important}
.medal-tabs{display:flex!important;gap:8px!important;flex-wrap:wrap!important}.medal-tab{border:1px solid #e2e8f0!important;background:#fff!important;color:#475569!important;border-radius:999px!important;padding:9px 14px!important;font-weight:950!important;cursor:pointer!important}.medal-tab.active{background:#0f172a!important;color:#fff!important;border-color:#0f172a!important}.library-hint{font-size:12px!important;color:#64748b!important;font-weight:800!important}
.quality-tabs{display:flex!important;gap:7px!important;flex-wrap:wrap!important;margin:0 0 14px!important;padding:10px!important;border-radius:20px!important;background:#f8fafc!important;border:1px solid #e2e8f0!important}.quality-tab{border:1px solid #e2e8f0!important;background:#fff!important;color:#64748b!important;border-radius:999px!important;padding:7px 12px!important;font-size:12px!important;font-weight:950!important;cursor:pointer!important}.quality-tab.active{background:color-mix(in srgb,var(--quality-color,#2563eb) 12%,#fff)!important;border-color:color-mix(in srgb,var(--quality-color,#2563eb) 34%,#fff)!important;color:var(--quality-color,#1d4ed8)!important}
.medal-grid{display:grid!important;grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:12px!important}
.library-card{min-height:108px!important;border:1px solid #e2e8f0!important;border-radius:22px!important;background:#fff!important;position:relative!important;transition:.16s ease!important;overflow:hidden!important;display:grid!important;place-items:center!important;padding:14px!important}.library-card.owned{border:2px solid var(--quality-color,#64748b)!important;box-shadow:0 0 12px color-mix(in srgb,var(--quality-color,#64748b) 22%,transparent)!important}.library-card.locked{filter:grayscale(1)!important;opacity:.48!important}.library-card:hover{transform:translateY(-2px)!important;box-shadow:0 16px 32px rgba(15,23,42,.08)!important}.library-card.equipped{border:2px solid var(--quality-color,#64748b)!important;box-shadow:0 0 16px color-mix(in srgb,var(--quality-color,#64748b) 32%,transparent)!important}.library-status{display:none!important}.library-medal{border:0!important;background:transparent!important;padding:0!important;cursor:pointer!important}.library-medal img{width:68px!important;height:68px!important;object-fit:contain!important;filter:drop-shadow(0 6px 12px rgba(15,23,42,.1))!important}.library-empty{grid-column:1/-1!important;text-align:center!important;color:#94a3b8!important;font-weight:900!important;padding:28px!important}
.library-pager{display:flex!important;gap:6px!important;flex-wrap:wrap!important;justify-content:center!important;margin-top:14px!important}.page-btn{border:1px solid #e2e8f0!important;background:#fff!important;color:#475569!important;border-radius:999px!important;padding:7px 12px!important;font-size:12px!important;font-weight:900!important;cursor:pointer!important}.page-btn.active{background:#0f172a!important;color:#fff!important;border-color:#0f172a!important}.page-btn[disabled]{opacity:.4!important;cursor:not-allowed!important}
.medal-modal{position:fixed!important;inset:0!important;z-index:1100!important;display:none!important;align-items:center!important;justify-content:center!important}.medal-modal.open{display:flex!important}.medal-modal-mask{position:absolute!important;inset:0!important;background:rgba(15,23,42,.45)!important}.medal-modal-card{position:relative!important;width:min(400px,calc(100% - 32px))!important;background:#fff!important;border-radius:26px!important;padding:28px!important;text-align:center!important;box-shadow:0 28px 80px rgba(15,23,42,.28)!important;z-index:1!important}.modal-close{position:absolute!important;right:14px!important;top:12px!important;border:0!important;background:transparent!important;color:#94a3b8!important;cursor:pointer!important}.modal-close svg{width:22px!important;height:22px!important}.modal-icon{margin-bottom:12px!important}.modal-icon img{width:80px!important;height:80px!important;object-fit:contain!important}.medal-modal-card h3{margin:0 0 8px!important;font-size:20px!important;color:#0f172a!important}.modal-desc{margin:0 0 12px!important;color:#64748b!important;font-size:14px!important;line-height:1.65!important}.modal-meta{display:flex!important;flex-direction:column!important;gap:6px!important;margin-bottom:16px!important;font-size:13px!important;color:#475569!important}.modal-actions{display:flex!important;gap:10px!important;justify-content:center!important}.modal-action{border:0!important;border-radius:999px!important;background:#0f172a!important;color:#fff!important;padding:10px 20px!important;font-size:13px!important;font-weight:900!important;cursor:pointer!important;text-decoration:none!important}.modal-action.danger{background:#ef4444!important}
.medal-toast{position:fixed!important;left:50%!important;bottom:112px!important;transform:translateX(-50%)!important;z-index:90!important;min-width:220px!important;max-width:92vw!important;padding:14px 22px!important;border-radius:999px!important;background:#0f172a!important;color:#fff!important;font-size:14px!important;font-weight:800!important;text-align:center!important;opacity:0!important;pointer-events:none!important;transition:opacity .18s ease,transform .18s ease!important}.medal-toast.show{opacity:1!important;pointer-events:auto!important;transform:translateX(-50%) translateY(0)!important}
html[data-theme="dark"] .medal-page{background:#0b1120!important}html[data-theme="dark"] .medal-panel,html[data-theme="dark"] .library-card,html[data-theme="dark"] .side-stat{background:#111827!important;border-color:#263244!important;color:#e5e7eb!important}html[data-theme="dark"] .medal-panel h2,html[data-theme="dark"] .library-card .library-medal{color:#e5e7eb!important}html[data-theme="dark"] .medal-panel p,html[data-theme="dark"] .library-hint{color:#94a3b8!important}html[data-theme="dark"] .medal-slot{background:#0f172a!important;border-color:#334155!important}html[data-theme="dark"] .medal-tab{background:#111827!important;border-color:#263244!important;color:#cbd5e1!important}html[data-theme="dark"] .medal-tab.active{background:#2563eb!important;color:#fff!important;border-color:#2563eb!important}html[data-theme="dark"] .quality-tab{background:#111827!important;border-color:#263244!important;color:#94a3b8!important}html[data-theme="dark"] .quality-tab.active{color:#fff!important}html[data-theme="dark"] .medal-modal-card{background:#111827!important}html[data-theme="dark"] .medal-modal-card h3{color:#e5e7eb!important}html[data-theme="dark"] .page-btn{background:#111827!important;border-color:#263244!important;color:#cbd5e1!important}html[data-theme="dark"] .page-btn.active{background:#2563eb!important;color:#fff!important}
@media(max-width:980px){.medal-board{grid-template-columns:1fr!important}.medal-grid{grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:10px!important}.library-card{min-height:88px!important;padding:10px!important;border-radius:18px!important}.library-medal img,.library-medal svg{width:56px!important;height:56px!important}}@media(max-width:640px){.medal-page{padding:0 12px 160px!important}.medal-hero{border-radius:24px!important;padding:22px!important;align-items:flex-start!important;flex-direction:column!important}.medal-hero h1{font-size:28px!important}.medal-grid{grid-template-columns:repeat(4,minmax(0,1fr))!important;gap:8px!important}.library-card{min-height:72px!important;padding:8px!important;border-radius:16px!important}.library-medal img,.library-medal svg{width:44px!important;height:44px!important}.medal-slots{gap:6px!important}.medal-slot{min-height:76px!important;border-radius:16px!important}.medal-slot img{width:36px!important;height:36px!important}.slot-empty span{width:30px!important;height:30px!important;border-radius:10px!important}.medal-side-stats{display:grid!important;grid-template-columns:1fr 1fr!important}.side-stat strong{font-size:22px!important}}
</style>
<main class="medal-page">
<?php if (!empty($error)): ?><div class="medal-alert error"><?= htmlspecialchars($error) ?></div><?php endif; ?>
  <div class="medal-shell" id="medalApp" data-logged-in="<?= $userId > 0 ? '1' : '0' ?>">
    <section class="medal-board">
      <div class="medal-panel medal-slots-panel">
        <div class="medal-panel-head"><div><h2>我的展示位</h2><p>最多佩戴 5 个勋章，仅显示图标。点击图标查看详情。</p></div><div class="medal-count"><span id="equippedCount"><?= (int)$equippedCount ?></span> / 5</div></div>
        <div class="medal-slots" id="medalSlots" aria-label="勋章展示位"></div>
      </div>
      <aside class="medal-panel medal-side-stats">
        <div class="side-stat"><strong><?= (int)$ownedCount ?></strong><span>已获得</span></div>
        <div class="side-stat"><strong><?= count($medals ?? []) ?></strong><span>全部勋章</span></div>
      </aside>
    </section>
    <section class="medal-panel medal-library">
      <div class="library-top"><div class="medal-tabs"><button class="medal-tab active" type="button" data-tab="all">全部勋章</button><button class="medal-tab" type="button" data-tab="mine">我的勋章</button></div><div class="library-hint">已拥有的勋章可拖拽到上方展示位</div></div>
      <div class="quality-tabs" id="qualityTabs" aria-label="勋章品质筛选"></div>
      <div class="medal-grid" id="medalGrid"></div>
      <div class="library-pager" id="libraryPager" aria-label="勋章分页"></div>
    </section>
  </div>
</main>
<div class="medal-modal" id="medalModal" aria-hidden="true">
  <div class="medal-modal-mask" data-modal-close></div>
  <div class="medal-modal-card" role="dialog" aria-modal="true" aria-labelledby="modalMedalName">
    <button class="modal-close" type="button" data-modal-close aria-label="关闭"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 6 6 18M6 6l12 12"/></svg></button>
    <div class="modal-icon" id="modalIcon"></div>
    <h3 id="modalMedalName"></h3>
    <p class="modal-desc" id="modalDesc"></p>
    <div class="modal-meta"><div id="modalOwned"></div><div id="modalRule"></div></div>
    <div class="modal-actions" id="modalActions"></div>
  </div>
</div>
<div class="medal-toast" id="medalToast"></div>
<script>
(function(){
  var loggedIn=<?= $userId > 0 ? 'true' : 'false' ?>;
  var csrf=<?= json_encode($csrf, JSON_UNESCAPED_UNICODE) ?>;
  var medals=<?= json_encode($clientMedals, JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>;
  var slots=<?= json_encode($slotValues, JSON_UNESCAPED_UNICODE) ?>.map(function(x){return x?parseInt(x,10):null;}).slice(0,5);
  while(slots.length<5)slots.push(null);
  var tab='all', quality='all', page=1, pageSize=18, drag=null, saving=false;
  var qualities=<?= json_encode(array_merge([['code'=>'all','name'=>'全部品质','color'=>'#2563eb','badge_count'=>count($medals ?? [])]], array_map(function($q){ return ['code'=>(string)($q['code'] ?? ''),'name'=>(string)($q['name'] ?? ''),'color'=>preg_match('/^#[0-9a-fA-F]{6}$/', (string)($q['color'] ?? '')) ? (string)$q['color'] : '#64748b','badge_count'=>(int)($q['badge_count'] ?? 0)]; }, $qualities ?? [])), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>;
  var slotBox=document.getElementById('medalSlots'), grid=document.getElementById('medalGrid'), pager=document.getElementById('libraryPager'), qualityTabs=document.getElementById('qualityTabs'), toast=document.getElementById('medalToast');
  function byId(id){return medals.find(function(m){return parseInt(m.id,10)===parseInt(id,10);})||null;}
  function esc(s){return String(s||'').replace(/[&<>"']/g,function(c){return {'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c];});}
  function icon(m){return m&&m.icon?'<img src="'+esc(m.icon)+'" alt="" loading="lazy">':'<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="8" r="4"/><path d="M8.5 12.5 7 21l5-3 5 3-1.5-8.5"/></svg>';}
  function toastMsg(msg,bad){toast.textContent=msg;toast.style.background=bad?'rgba(153,27,27,.94)':'rgba(15,23,42,.92)';toast.classList.add('show');clearTimeout(toast._t);toast._t=setTimeout(function(){toast.classList.remove('show');},1800);}
  function cleanSlots(arr){var out=[];arr.forEach(function(id){id=parseInt(id||0,10); if(id>0 && out.indexOf(id)===-1) out.push(id);}); while(out.length<5)out.push(null); return out.slice(0,5);}
  function save(action){if(!loggedIn)return;var oldSlots=slots.slice();slots=cleanSlots(slots);document.getElementById('equippedCount').textContent=slots.filter(Boolean).length;if(saving)return; saving=true; var fd=new FormData();fd.append('_csrf_token',csrf);fd.append('_action','layout');fd.append('slots',JSON.stringify(slots.filter(Boolean)));fetch('/index.php?path=medals',{method:'POST',body:fd,credentials:'same-origin',headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json'}}).then(function(r){return r.json().catch(function(){return {ok:false,error:'保存失败'};});}).then(function(d){if(!d.ok)throw new Error(d.error||'保存失败'); medals.forEach(function(m){var i=slots.indexOf(m.id);m.equipped=i!==-1;m.slot=i+1;}); render(); var added=[];var removed=[];for(var i=0;i<5;i++){var o=oldSlots[i]||null;var n=slots[i]||null;if(o!==n){if(n&&oldSlots.indexOf(n)===-1){var m=byId(n);if(m)added.push(m.name);}if(o&&slots.indexOf(o)===-1){var m=byId(o);if(m)removed.push(m.name);}}}var msg='已保存展示位';if(added.length===1&&removed.length===0)msg='已装备「'+added[0]+'」';else if(removed.length===1&&added.length===0)msg='已卸下「'+removed[0]+'」';else if(added.length>0&&removed.length===0)msg='已装备 '+added.length+' 个勋章';else if(removed.length>0&&added.length===0)msg='已卸下 '+removed.length+' 个勋章';toastMsg(msg);}).catch(function(e){toastMsg(e.message||'保存失败',true);}).finally(function(){saving=false;});}
  function renderSlots(){slotBox.innerHTML='';slots=cleanSlots(slots);slots.forEach(function(id,i){var m=byId(id);var slot=document.createElement('div');slot.className='medal-slot'+(m?' is-filled':'');slot.dataset.slot=i;slot.innerHTML='<span class="slot-index">'+(i+1)+'</span>'+(m?'<button class="slot-medal" type="button" draggable="true" data-id="'+m.id+'" title="'+esc(m.name)+'">'+icon(m)+'</button><button class="slot-remove" type="button" data-remove="'+i+'" aria-label="卸下"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 6 6 18M6 6l12 12"/></svg></button>':'<div class="slot-empty"><span></span>空位</div>');slotBox.appendChild(slot);});document.getElementById('equippedCount').textContent=slots.filter(Boolean).length;}
  function renderQualityTabs(){if(!qualityTabs)return;qualityTabs.style.display=tab==='all'?'flex':'none';qualityTabs.innerHTML=qualities.map(function(q){var key=q.code||'all';var count=medals.filter(function(m){return !m.owned&&(key==='all'||m.level===key);}).length;return '<button class="quality-tab '+(quality===key?'active':'')+'" type="button" data-quality="'+esc(key)+'" style="--quality-color:'+esc(q.color||'#2563eb')+'">'+esc(q.name||key)+' <span>'+count+'</span></button>';}).join('');}
  function filteredList(){return medals.filter(function(m){if(tab==='mine')return m.owned;if(m.owned)return false;if(quality!=='all'&&m.level!==quality)return false;return true;});}
  function renderPager(total){if(!pager)return;var pages=Math.max(1,Math.ceil(total/pageSize));if(page>pages)page=pages;pager.style.display=pages>1?'flex':'none';var html='<button class="page-btn" type="button" data-page="prev" '+(page<=1?'disabled':'')+'>上一页</button>';for(var i=1;i<=pages;i++){html+='<button class="page-btn '+(i===page?'active':'')+'" type="button" data-page="'+i+'">'+i+'</button>';}html+='<button class="page-btn" type="button" data-page="next" '+(page>=pages?'disabled':'')+'>下一页</button>';pager.innerHTML=html;}
  function renderGrid(){var list=filteredList();var total=list.length;renderPager(total);var start=(page-1)*pageSize;list=list.slice(start,start+pageSize);grid.innerHTML=list.map(function(m){var cls='library-card '+(m.owned?'owned can-drag':'locked')+(slots.indexOf(m.id)!==-1?' equipped':'');return '<article class="'+cls+'" data-id="'+m.id+'" style="--quality-color:'+esc(m.level_color||'#64748b')+'"><button class="library-medal" type="button" '+(m.owned&&loggedIn?'draggable="true"':'')+' data-id="'+m.id+'" title="'+esc(m.name)+'">'+icon(m)+'</button></article>';}).join('') || '<div class="library-empty">'+(tab==='mine'?'暂无已获得勋章':'当前品质暂无勋章')+'</div>';}
  function render(){renderSlots();renderQualityTabs();renderGrid();}
  function openModal(id){var m=byId(id); if(!m)return;document.getElementById('modalIcon').innerHTML=icon(m);document.getElementById('modalMedalName').textContent=m.name;document.getElementById('modalDesc').textContent=m.description||'暂无勋章说明';document.getElementById('modalOwned').textContent=m.owned?(m.equipped?'状态：已佩戴':'状态：已拥有'):'状态：未获得';document.getElementById('modalRule').textContent=m.rule||'由管理员手动发放';var actions=document.getElementById('modalActions');actions.innerHTML='';if(loggedIn&&m.owned){var idx=slots.indexOf(m.id);var btn=document.createElement('button');btn.className='modal-action '+(idx!==-1?'danger':'');btn.type='button';btn.textContent=idx!==-1?'卸下勋章':'佩戴到空位';btn.onclick=function(){if(idx!==-1){slots[idx]=null;}else{var empty=slots.indexOf(null);if(empty===-1){toastMsg('展示位已满，请先卸下一个勋章',true);return;}slots[empty]=m.id;}closeModal();save();render();};actions.appendChild(btn);}else if(loggedIn&&!m.owned&&m.obtain_method==='free'){var fb=document.createElement('button');fb.className='modal-action';fb.type='button';fb.textContent='免费领取';fb.onclick=function(){medalAction('claim_badge',m.id);};actions.appendChild(fb);}else if(loggedIn&&!m.owned&&m.obtain_method==='shop'){var sb=document.createElement('button');sb.className='modal-action';sb.type='button';sb.disabled=!m.can_afford;sb.textContent=m.can_afford?('购买 '+(m.price_label||'')):'余额不足';sb.onclick=function(){if(m.can_afford&&confirm('确认花费 '+(m.price_label||'')+' 购买该勋章？'))medalAction('buy_badge',m.id);};actions.appendChild(sb);}else if(!loggedIn){var a=document.createElement('a');a.className='modal-action';a.href='/index.php?path=login&redirect='+encodeURIComponent('/index.php?path=medals');a.textContent='登录后管理';actions.appendChild(a);}document.getElementById('medalModal').classList.add('open');document.getElementById('medalModal').setAttribute('aria-hidden','false');}
  function medalAction(act,bid){var fd=new FormData();fd.append('_csrf_token',csrf);fd.append('_action',act);fd.append('badge_id',bid);fetch('/index.php?path=decoration&tab=medals',{method:'POST',body:fd,credentials:'same-origin',headers:{'X-Requested-With':'XMLHttpRequest','Accept':'application/json'}}).then(function(r){return r.json().catch(function(){return{ok:false,error:'操作失败'};});}).then(function(d){if(!d.ok)throw new Error(d.error||'操作失败');var m=byId(bid);if(m)m.owned=true;closeModal();render();toastMsg(act==='claim_badge'?'领取成功':'购买成功');}).catch(function(e){toastMsg(e.message||'操作失败',true);});}
  function closeModal(){var modal=document.getElementById('medalModal');modal.classList.remove('open');modal.setAttribute('aria-hidden','true');}
  document.querySelectorAll('.medal-tab').forEach(function(b){b.addEventListener('click',function(){document.querySelectorAll('.medal-tab').forEach(function(x){x.classList.remove('active');});b.classList.add('active');tab=b.dataset.tab;quality='all';page=1;render();});});
  document.addEventListener('click',function(e){var q=e.target.closest('#qualityTabs .quality-tab');if(q){quality=q.dataset.quality||'all';page=1;render();return;}var pg=e.target.closest('.page-btn');if(pg&&!pg.disabled){var total=filteredList().length,pages=Math.max(1,Math.ceil(total/pageSize));var val=pg.dataset.page;if(val==='prev')page=Math.max(1,page-1);else if(val==='next')page=Math.min(pages,page+1);else page=parseInt(val,10)||1;renderGrid();return;}var close=e.target.closest('[data-modal-close]');if(close){closeModal();return;}var remove=e.target.closest('[data-remove]');if(remove){slots[parseInt(remove.dataset.remove,10)]=null;save();render();return;}var medal=e.target.closest('.slot-medal,.library-medal');if(medal){openModal(parseInt(medal.dataset.id,10));}});
  document.addEventListener('dragstart',function(e){var el=e.target.closest('.slot-medal,.library-medal');if(!el||!loggedIn)return;var id=parseInt(el.dataset.id,10), m=byId(id);if(!m||!m.owned){e.preventDefault();return;}drag={id:id,fromSlot:el.closest('.medal-slot')?parseInt(el.closest('.medal-slot').dataset.slot,10):null};e.dataTransfer.effectAllowed='move';e.dataTransfer.setData('text/plain',String(id));});
  document.addEventListener('dragover',function(e){var slot=e.target.closest('.medal-slot');if(slot){e.preventDefault();slot.classList.add('is-over');}});
  document.addEventListener('dragleave',function(e){var slot=e.target.closest('.medal-slot');if(slot)slot.classList.remove('is-over');});
  document.addEventListener('drop',function(e){var slot=e.target.closest('.medal-slot');document.querySelectorAll('.is-over').forEach(function(x){x.classList.remove('is-over');});if(!drag)return;if(slot){e.preventDefault();var target=parseInt(slot.dataset.slot,10);var existing=slots[target];var old=slots.indexOf(drag.id);if(old!==-1)slots[old]=null;if(drag.fromSlot!==null&&existing){slots[drag.fromSlot]=existing;}slots[target]=drag.id;save();render();drag=null;}});
  document.addEventListener('keydown',function(e){if(e.key==='Escape')closeModal();});
  render();
})();
</script>
