<?php
$pageTitle=((string)($_GET['path'] ?? '') === 'tasks') ? '任务中心' : '成长系统'; require dirname(__DIR__) . '/layouts/main.php';
$tab=$tab??'levels'; $levels=$levels??[]; $tasks=$tasks??[]; $users=$users??[]; $expLogs=$expLogs??[]; $submissions=$submissions??[]; $checkinSettings=$checkinSettings??[]; $checkinRows=$checkinRows??[]; $checkinStats=$checkinStats??[]; $currencies=$currencies??[]; $actions=$actions??[]; $categories=$categories??[]; $category=$category??'';
function growth_reward_text(array $task): string { return (new \App\Services\TaskService())->rewardText($task); }
function growth_admin_action_label(string $action, string $remark = ''): string {
    if ($action === 'task_reward') {
        if (preg_match('/完成任务「([^」]+)」/u', $remark, $m)) return '完成任务：' . $m[1];
        return '完成任务';
    }
    return [
        'login_daily'=>'每日登录', 'thread_publish'=>'发布帖子', 'post_publish'=>'发布回复',
        'thread_liked'=>'帖子被点赞', 'post_liked'=>'回复被点赞', 'email_verified'=>'邮箱验证',
        'verification_approved'=>'认证通过', 'thread_reward_sent'=>'打赏他人', 'thread_reward_received'=>'收到打赏',
        'profile_completed'=>'完善资料', 'follow_user'=>'关注用户', 'favorite_thread'=>'收藏帖子', 'oauth_bound'=>'绑定登录方式',
        'admin_adjust'=>'后台调整', 'daily_checkin'=>'每日签到'
    ][$action] ?? $action;
}
?>

<div class="page-header"><div><div class="page-title"><?= htmlspecialchars($pageTitle) ?></div><div class="admin-muted admin-mt-4">等级、任务、经验流水与任务审核统一管理。</div></div></div>
<div class="growth-tabs"><a class="<?= $tab==='levels'?'active':'' ?>" href="/admin.php?path=growth&tab=levels">等级配置</a><a class="<?= $tab==='tasks'?'active':'' ?>" href="/admin.php?path=<?= ((string)($_GET['path'] ?? '') === 'tasks') ? 'tasks' : 'growth' ?>&tab=tasks">任务管理</a><a class="<?= $tab==='checkin'?'active':'' ?>" href="/admin.php?path=growth&tab=checkin">签到管理</a><a class="<?= $tab==='users'?'active':'' ?>" href="/admin.php?path=growth&tab=users">用户成长</a><a class="<?= $tab==='logs'?'active':'' ?>" href="/admin.php?path=growth&tab=logs">经验流水</a><a class="<?= $tab==='submissions'?'active':'' ?>" href="/admin.php?path=<?= ((string)($_GET['path'] ?? '') === 'tasks') ? 'tasks' : 'growth' ?>&tab=submissions">任务审核</a></div>
<?php if($tab==='levels'): ?>
<div class="growth-card"><h3>新增等级</h3><form method="post" action="/admin.php?path=growth/level" data-no-ajax class="admin-form-grid"><?= csrf_field() ?><input class="input" type="number" name="level" placeholder="等级" required><input class="input" name="name" placeholder="等级名称" required><input class="input" type="number" name="min_exp" placeholder="所需经验" required><input class="input" type="color" name="color" value="#64748b"><select class="select" name="status"><option value="active">启用</option><option value="inactive">停用</option></select><input class="input" type="number" name="sort_order" value="0"><button class="btn">新增等级</button></form></div>
<div class="table-responsive"><table class="table growth-level-table"><thead><tr><th>显示</th><th>等级</th><th>名称</th><th>所需经验</th><th>颜色</th><th>状态</th><th>排序</th><th>操作</th></tr></thead><tbody><?php foreach($levels as $l): ?><tr><form method="post" action="/admin.php?path=growth/level" data-no-ajax><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$l['id'] ?>"><td><span class="level-pill admin-dynamic-var" style="--c:<?= htmlspecialchars($l['color']) ?>">Lv.<?= (int)$l['level'] ?></span></td><td><input class="input" type="number" name="level" value="<?= (int)$l['level'] ?>" <?= (int)$l['level'] === 1 ? 'readonly' : '' ?>></td><td><input class="input" name="name" value="<?= htmlspecialchars($l['name']) ?>"></td><td><input class="input" type="number" name="min_exp" value="<?= (int)$l['min_exp'] ?>"></td><td><input class="input" type="color" name="color" value="<?= htmlspecialchars($l['color']) ?>"></td><td><select class="select" name="status"><option value="active" <?= $l['status']==='active'?'selected':'' ?>>启用</option><option value="inactive" <?= $l['status']!=='active'?'selected':'' ?>>停用</option></select></td><td><input class="input" type="number" name="sort_order" value="<?= (int)$l['sort_order'] ?>"></td><td class="compact-actions"><button class="btn btn-light">保存</button></form><form method="post" action="/admin.php?path=growth/level/delete" data-no-ajax onsubmit="return confirm('确认删除该等级？')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$l['id'] ?>"><button class="btn btn-light admin-danger" <?= (int)$l['level'] === 1 ? 'disabled' : '' ?>>删除</button></form></td></tr><?php endforeach; ?></tbody></table></div>
<?php elseif($tab==='checkin'): ?>
<div class="checkin-stats"><div class="checkin-stat"><span>今日签到</span><b><?= (int)($checkinStats['today'] ?? 0) ?></b></div><div class="checkin-stat"><span>累计用户</span><b><?= (int)($checkinStats['total_users'] ?? 0) ?></b></div><div class="checkin-stat"><span>最高连续</span><b><?= (int)($checkinStats['max_streak'] ?? 0) ?></b></div><div class="checkin-stat"><span>累计签到</span><b><?= (int)($checkinStats['total'] ?? 0) ?></b></div></div>
<form method="post" action="/admin.php?path=growth/checkin" data-no-ajax><?= csrf_field() ?><div class="checkin-admin-hero"><section class="checkin-setting-panel"><div class="checkin-setting-head"><div><h3>签到设置</h3><div class="mini-note">7 天为一轮，经验进入成长等级；货币写入钱包流水 daily_checkin。</div></div><button class="btn">保存设置</button></div><div class="checkin-switch-row"><label>启用签到<select class="select" name="checkin_enabled"><option value="1" <?= !empty($checkinSettings['enabled'])?'selected':'' ?>>开启</option><option value="0" <?= empty($checkinSettings['enabled'])?'selected':'' ?>>关闭</option></select></label></div><div class="checkin-admin-grid admin-mt-14"><?php for($i=0;$i<7;$i++): ?><div class="checkin-admin-day"><b>第 <?= $i+1 ?> 天</b><label>经验奖励<input class="input" type="number" min="0" name="checkin_exp_rewards[]" value="<?= (int)($checkinSettings['exp_rewards'][$i] ?? 0) ?>"></label><label>货币类型<select class="select" name="checkin_currency_rewards[]"><?php foreach($currencies as $c): ?><option value="<?= htmlspecialchars($c['code']) ?>" <?= (($checkinSettings['currency_rewards'][$i] ?? $checkinSettings['currency'] ?? '')===$c['code'])?'selected':'' ?>><?= htmlspecialchars($c['name']) ?></option><?php endforeach; ?></select></label><label>货币数量<input class="input" type="number" min="0" step="0.000001" name="checkin_coin_rewards[]" value="<?= htmlspecialchars((string)($checkinSettings['coin_rewards'][$i] ?? 0)) ?>"></label></div><?php endfor; ?></div></section><aside class="checkin-preview"><div class="checkin-preview-title">前台奖励预览</div><div class="checkin-preview-list"><?php for($i=0;$i<7;$i++): ?><div class="checkin-preview-row"><em>Day <?= $i+1 ?></em><div class="checkin-preview-bar"><span class="admin-dynamic-width" style="width:<?= (int)round((($i+1)/7)*100) ?>%"></span></div><strong>+<?= (int)($checkinSettings['exp_rewards'][$i] ?? 0) ?> 经验 / +<?= currency_trim_amount((float)($checkinSettings['coin_rewards'][$i] ?? 0)) ?> <?= htmlspecialchars(currency_name_by_code((string)($checkinSettings['currency_rewards'][$i] ?? $checkinSettings['currency'] ?? ''))) ?></strong></div><?php endfor; ?></div></aside></div></form>
<div class="growth-card admin-mt-14"><h3>最近签到</h3><?php if(empty($checkinRows)): ?><div class="mini-note">暂无签到记录。</div><?php else: ?><div class="table-responsive"><table class="table"><thead><tr><th>用户</th><th>日期</th><th>连续</th><th>奖励</th><th>时间</th></tr></thead><tbody><?php foreach($checkinRows as $r): ?><tr><td><?= user_avatar_html($r,'user-avatar',30) ?> <?= htmlspecialchars(($r['nickname'] ?? '') ?: ($r['username'] ?? ('UID '.$r['user_id']))) ?></td><td><?= htmlspecialchars($r['checkin_date']) ?></td><td><?= (int)$r['streak_days'] ?> 天</td><td>+<?= (int)$r['reward_exp'] ?> 经验<?php if(!empty($r['reward_currency_code'])): ?> / +<?= currency_trim_amount((float)$r['reward_currency_amount']) ?> <?= htmlspecialchars(currency_name_by_code((string)$r['reward_currency_code'])) ?><?php endif; ?></td><td><?= htmlspecialchars($r['created_at']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?></div>
<?php elseif($tab==='tasks'): ?>
<div class="growth-card"><h3>新增任务</h3><form method="post" action="/admin.php?path=<?= ((string)($_GET['path'] ?? '') === 'tasks') ? 'tasks/task' : 'growth/task' ?>" data-no-ajax class="admin-form-grid"><?= csrf_field() ?><input class="input" name="title" placeholder="任务名称" required><input class="input" name="description" placeholder="任务说明"><select class="select" name="category"><?php foreach($categories as $ck=>$cv): ?><option value="<?= htmlspecialchars($ck) ?>"><?= htmlspecialchars($cv) ?></option><?php endforeach; ?></select><select class="select" name="action"><?php foreach($actions as $k=>$v): ?><option value="<?= htmlspecialchars($k) ?>"><?= htmlspecialchars($v) ?></option><?php endforeach; ?></select><select class="select" name="cycle_type"><option value="once">一次性</option><option value="daily">每日</option><option value="weekly">每周</option><option value="monthly">每月</option><option value="permanent">长期</option><option value="limited">限时</option></select><input class="input" type="number" name="target_count" value="1" placeholder="目标次数"><input class="input" type="number" name="reward_exp" value="0" placeholder="奖励经验"><label class="admin-muted"><input type="checkbox" name="manual_review" value="1"> 手动审核</label><label class="admin-muted"><input type="checkbox" name="claim_required" value="1"> 需手动领取</label><label class="admin-muted"><input type="checkbox" name="once_per_ref" value="1"> 同来源只算一次</label><select class="select" name="status"><option value="active">启用</option><option value="inactive">停用</option></select><input class="input" type="number" name="sort_order" value="0"><div class="reward-lines"><div class="reward-line"><select class="select" name="reward_currency_code[]"><option value="">不奖励货币</option><?php foreach($currencies as $c): ?><option value="<?= htmlspecialchars($c['code']) ?>"><?= htmlspecialchars($c['name']) ?></option><?php endforeach; ?></select><input class="input" name="reward_currency_amount[]" placeholder="数量"></div></div><button class="btn">新增任务</button></form></div>
<form class="filter-row" method="get" action="/admin.php"><input type="hidden" name="path" value="<?= ((string)($_GET['path'] ?? '') === 'tasks') ? 'tasks' : 'growth' ?>"><input type="hidden" name="tab" value="tasks"><select class="select" name="category"><option value="">全部分类</option><?php foreach($categories as $ck=>$cv): ?><option value="<?= htmlspecialchars($ck) ?>" <?= $category===$ck?'selected':'' ?>><?= htmlspecialchars($cv) ?></option><?php endforeach; ?></select><button class="btn">筛选</button></form><div class="table-responsive"><table class="table"><thead><tr><th>ID</th><th>任务</th><th>分类/动作/周期</th><th>目标</th><th>奖励</th><th>模式</th><th>状态</th><th>操作</th></tr></thead><tbody><?php foreach($tasks as $t): ?><tr><td><strong>#<?= (int)$t['id'] ?></strong></td><td><strong><?= htmlspecialchars($t['title']) ?></strong><div class="mini-note"><?= htmlspecialchars((string)$t['description']) ?></div></td><td><?= htmlspecialchars($categories[$t['category'] ?? 'normal'] ?? ($t['category'] ?? '普通任务')) ?><div class="mini-note"><?= htmlspecialchars($actions[$t['action']] ?? $t['action']) ?> / <?= htmlspecialchars($t['cycle_type']) ?></div></td><td><?= (int)$t['target_count'] ?></td><td><?= htmlspecialchars(growth_reward_text($t)) ?></td><td><div class="mini-note"><?= !empty($t['manual_review'])?'手动审核':'自动' ?> / <?= !empty($t['claim_required'])?'手动领取':'自动发放' ?></div></td><td><?= htmlspecialchars($t['status']) ?></td><td class="compact-actions"><form method="post" action="/admin.php?path=<?= ((string)($_GET['path'] ?? '') === 'tasks') ? 'tasks/task/delete' : 'growth/task/delete' ?>" data-no-ajax onsubmit="return confirm('确认删除该任务？')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$t['id'] ?>"><button class="btn btn-light admin-danger">删除</button></form></td></tr><?php endforeach; ?></tbody></table></div>
<?php elseif($tab==='users'): ?>
<form class="filter-row" method="get" action="/admin.php"><input type="hidden" name="path" value="growth"><input type="hidden" name="tab" value="users"><input class="input" name="kw" placeholder="用户ID/用户名/昵称" value="<?= htmlspecialchars($_GET['kw'] ?? '') ?>"><button class="btn">筛选</button></form>
<div class="table-responsive"><table class="table"><thead><tr><th>用户</th><th>等级</th><th>经验</th><th>今日经验</th><th>调整经验</th></tr></thead><tbody><?php foreach($users as $u): ?><tr><td><?= user_avatar_html($u,'user-avatar',34) ?> <?= htmlspecialchars($u['nickname'] ?: $u['username']) ?><div class="mini-note">UID <?= (int)$u['id'] ?></div></td><td><span class="level-pill admin-dynamic-var" style="--c:<?= htmlspecialchars($u['level_color'] ?? '#64748b') ?>">Lv.<?= (int)$u['current_level'] ?> <?= htmlspecialchars($u['level_name'] ?? '') ?></span></td><td><?= (int)$u['total_exp'] ?></td><td><?= (int)$u['today_exp'] ?></td><td><form class="compact-actions" method="post" action="/admin.php?path=growth/adjust" data-no-ajax><?= csrf_field() ?><input type="hidden" name="user_id" value="<?= (int)$u['id'] ?>"><input class="input" type="number" name="exp" placeholder="+/-经验" required><input class="input" name="remark" placeholder="原因" required><button class="btn btn-light">提交</button></form></td></tr><?php endforeach; ?></tbody></table></div>
<?php elseif($tab==='logs'): ?>
<form class="filter-row" method="get" action="/admin.php"><input type="hidden" name="path" value="growth"><input type="hidden" name="tab" value="logs"><input class="input" type="number" name="user_id" placeholder="用户ID" value="<?= htmlspecialchars($_GET['user_id'] ?? '') ?>"><button class="btn">筛选</button></form><div class="table-responsive"><table class="table"><thead><tr><th>ID</th><th>用户</th><th>动作</th><th>变化</th><th>经验</th><th>等级</th><th>备注</th><th>时间</th></tr></thead><tbody><?php foreach($expLogs as $l): ?><tr><td>#<?= (int)$l['id'] ?></td><td><?= htmlspecialchars(($l['nickname'] ?? '') ?: ($l['username'] ?? ('UID '.$l['user_id']))) ?><div class="mini-note">UID <?= (int)$l['user_id'] ?></div></td><td><?= htmlspecialchars(growth_admin_action_label((string)$l['action'], (string)$l['remark'])) ?></td><td class="admin-dynamic-color" style="color:<?= (int)$l['exp_change']>=0?'#16a34a':'#ef4444' ?>"><?= (int)$l['exp_change']>=0?'+':'' ?><?= (int)$l['exp_change'] ?></td><td><?= (int)$l['before_exp'] ?> → <?= (int)$l['after_exp'] ?></td><td>Lv.<?= (int)$l['before_level'] ?> → Lv.<?= (int)$l['after_level'] ?></td><td><?= htmlspecialchars((string)$l['remark']) ?></td><td><?= htmlspecialchars($l['created_at']) ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php else: ?>
<form class="filter-row" method="get" action="/admin.php"><input type="hidden" name="path" value="<?= ((string)($_GET['path'] ?? '') === 'tasks') ? 'tasks' : 'growth' ?>"><input type="hidden" name="tab" value="submissions"><select class="select" name="status"><option value="">全部状态</option><option value="pending" <?= (($_GET['status']??'')==='pending')?'selected':'' ?>>待审核</option><option value="approved" <?= (($_GET['status']??'')==='approved')?'selected':'' ?>>已通过</option><option value="rejected" <?= (($_GET['status']??'')==='rejected')?'selected':'' ?>>已驳回</option></select><button class="btn">筛选</button></form><div class="table-responsive"><table class="table"><thead><tr><th>ID</th><th>用户</th><th>任务</th><th>提交内容</th><th>状态</th><th>时间</th><th>审核</th></tr></thead><tbody><?php foreach($submissions as $s): ?><tr><td>#<?= (int)$s['id'] ?></td><td><?= user_avatar_html($s,'user-avatar',34) ?> <?= htmlspecialchars($s['nickname'] ?: $s['username']) ?></td><td><?= htmlspecialchars($s['task_title']) ?></td><td class="admin-table-title"><?= nl2br(htmlspecialchars((string)$s['content'])) ?><?php if(!empty($s['review_note'])): ?><div class="mini-note">审核备注：<?= htmlspecialchars($s['review_note']) ?></div><?php endif; ?></td><td><?= htmlspecialchars($s['status']) ?></td><td><?= htmlspecialchars($s['created_at']) ?></td><td><?php if($s['status']==='pending'): ?><div class="compact-actions"><form method="post" action="/admin.php?path=<?= ((string)($_GET['path'] ?? '') === 'tasks') ? 'tasks/submission/review' : 'growth/submission/review' ?>" data-no-ajax><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$s['id'] ?>"><input type="hidden" name="action" value="approve"><input class="input" name="note" placeholder="备注"><button class="btn">通过</button></form><form method="post" action="/admin.php?path=<?= ((string)($_GET['path'] ?? '') === 'tasks') ? 'tasks/submission/review' : 'growth/submission/review' ?>" data-no-ajax><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$s['id'] ?>"><input type="hidden" name="action" value="reject"><input class="input" name="note" placeholder="原因"><button class="btn btn-light admin-danger">驳回</button></form></div><?php else: ?><span class="mini-note">已处理</span><?php endif; ?></td></tr><?php endforeach; ?></tbody></table></div>
<?php endif; ?>
<?php require dirname(__DIR__) . '/layouts/main_footer.php'; ?>
