<?php $pageTitle='支付管理'; require dirname(__DIR__) . '/layouts/main.php'; $tab=$tab??'channels'; $channelNames=\App\Models\PaymentModel::CHANNELS; $canChannel=\App\Middleware\Permission::can('payment.channel'); $canPackage=\App\Middleware\Permission::can('payment.package'); $canManualPaid=\App\Middleware\Permission::can('payment.order.manual_paid'); $canDeleteOrder=\App\Middleware\Permission::can('payment.order.delete'); $canRedeem=\App\Middleware\Permission::can('payment.redeem.manage'); $canLogs=\App\Middleware\Permission::can('payment.logs.view'); ?>

<div class="page-header"><div><div class="page-title">支付管理</div><div class="admin-muted admin-mt-4">支付渠道、充值比例、订单、兑换码和回调日志统一管理。</div></div></div>
<div class="pay-tabs"><a class="<?= $tab==='channels'?'active':'' ?>" href="/admin.php?path=payments&tab=channels">支付方式</a><a class="<?= $tab==='packages'?'active':'' ?>" href="/admin.php?path=payments&tab=packages">充值比例</a><a class="<?= $tab==='orders'?'active':'' ?>" href="/admin.php?path=payments&tab=orders">支付订单</a><a class="<?= $tab==='redeem'?'active':'' ?>" href="/admin.php?path=payments&tab=redeem">兑换码</a><?php if($canLogs): ?><a class="<?= $tab==='logs'?'active':'' ?>" href="/admin.php?path=payments&tab=logs">回调日志</a><?php endif; ?></div>
<?php if($tab==='channels'): ?><?php if(!$canChannel): ?><div class="alert err">你没有修改支付方式的权限，仅可查看。</div><?php endif; ?><?php $activePayChannel=(string)($_GET['channel'] ?? ''); if($activePayChannel==='' || !isset($channels[$activePayChannel])) $activePayChannel=array_key_first($channels); ?><div class="pay-subtabs"><?php foreach($channels as $subCode=>$subCh): ?><a class="<?= $activePayChannel===$subCode?'active':'' ?>" href="/admin.php?path=payments&tab=channels&channel=<?= urlencode($subCode) ?>"><?= htmlspecialchars($channelNames[$subCode] ?? $subCh['name']) ?></a><?php endforeach; ?></div><?php foreach($channels as $code=>$ch): ?><?php if($code!==$activePayChannel) continue; ?><?php $cfg=json_decode((string)($ch['config_json']??'{}'),true)?:[]; ?><section class="pay-card"><h3><?= htmlspecialchars($channelNames[$code] ?? $ch['name']) ?></h3><form method="post" action="/admin.php?path=payments/channel" class="pay-grid"><?= csrf_field() ?><input type="hidden" name="code" value="<?= htmlspecialchars($code) ?>"><label>状态<select class="select" name="status"><option value="active" <?= ($ch['status']??'')==='active'?'selected':'' ?>>启用</option><option value="inactive" <?= ($ch['status']??'')!=='active'?'selected':'' ?>>关闭</option></select></label><label>排序<input class="input" type="number" name="sort_order" value="<?= (int)($ch['sort_order']??0) ?>"></label>
<?php if($code==='wechat_official'): ?>
  <label>AppID<input class="input" name="app_id" value="<?= htmlspecialchars($cfg['app_id']??'') ?>" placeholder="公众号/小程序/应用 AppID"></label>
  <label>商户号 mchid<input class="input" name="mch_id" value="<?= htmlspecialchars($cfg['mch_id']??'') ?>"></label>
  <label>商户证书序列号<input class="input" name="merchant_serial_no" value="<?= htmlspecialchars($cfg['merchant_serial_no']??'') ?>"></label>
  <label>API v3 密钥<input class="input" type="password" name="api_v3_key" value="<?= htmlspecialchars($cfg['api_v3_key']??'') ?>"></label>
  <label>交易类型<select class="select" name="trade_type"><option value="NATIVE" <?= (($cfg['trade_type']??'NATIVE')==='NATIVE')?'selected':'' ?>>Native 扫码支付</option><option value="JSAPI" <?= (($cfg['trade_type']??'')==='JSAPI')?'selected':'' ?>>JSAPI</option><option value="H5" <?= (($cfg['trade_type']??'')==='H5')?'selected':'' ?>>H5</option></select></label>
  <div class="callback-box"><strong>微信支付平台异步通知地址</strong><div class="copy-line"><input class="input" readonly value="<?= htmlspecialchars($callbackUrls[$code] ?? '') ?>"><button type="button" class="btn btn-light js-copy-pay-url">复制</button></div><div class="callback-tip">请在微信支付商户平台对应产品配置中填写此地址。下方 notify_url 一般留空；只有需要覆盖默认地址时才填写。</div></div>
  <label class="full-row">自定义异步通知地址 notify_url<input class="input" name="notify_url" value="<?= htmlspecialchars($cfg['notify_url']??'') ?>" placeholder="通常留空，默认使用上方地址"></label>
  <label class="full-row">商户 API 证书路径 apiclient_cert.pem<input class="input" name="apiclient_cert_path" value="<?= htmlspecialchars($cfg['apiclient_cert_path']??'') ?>" placeholder="建议放在 storage/keys/payments/ 下"></label>
  <label class="full-row">商户 API 私钥路径 apiclient_key.pem<input class="input" name="apiclient_key_path" value="<?= htmlspecialchars($cfg['apiclient_key_path']??'') ?>"></label>
  <label class="full-row">微信支付平台证书路径（验签用）<input class="input" name="platform_cert_path" value="<?= htmlspecialchars($cfg['platform_cert_path']??'') ?>"></label>
  <div class="mini full-row">微信支付 API v3 必填：AppID、商户号、商户证书序列号、API v3 密钥、商户证书/私钥、notify_url。Native 支付会返回 code_url 用于扫码。</div>
<?php elseif($code==='alipay_official'): ?>
  <label>应用 AppID<input class="input" name="app_id" value="<?= htmlspecialchars($cfg['app_id']??'') ?>"></label>
  <label>签名方式<select class="select" name="sign_type"><option value="RSA2" <?= (($cfg['sign_type']??'RSA2')==='RSA2')?'selected':'' ?>>RSA2</option><option value="RSA" <?= (($cfg['sign_type']??'')==='RSA')?'selected':'' ?>>RSA</option></select></label>
  <label>接口网关<input class="input" name="gateway" value="<?= htmlspecialchars($cfg['gateway']??'https://openapi.alipay.com/gateway.do') ?>"></label>
  <label>产品码<select class="select" name="product_code"><option value="FAST_INSTANT_TRADE_PAY" <?= (($cfg['product_code']??'FAST_INSTANT_TRADE_PAY')==='FAST_INSTANT_TRADE_PAY')?'selected':'' ?>>电脑网站支付</option><option value="FACE_TO_FACE_PAYMENT" <?= (($cfg['product_code']??'')==='FACE_TO_FACE_PAYMENT')?'selected':'' ?>>当面付</option></select></label>
  <div class="callback-box"><strong>支付宝开放平台异步通知回调地址</strong><div class="copy-line"><input class="input" readonly value="<?= htmlspecialchars($callbackUrls[$code] ?? '') ?>"><button type="button" class="btn btn-light js-copy-pay-url">复制</button></div><div class="callback-tip">复制后填写到支付宝开放平台/支付产品的异步通知地址。下方 notify_url 一般留空；只有需要覆盖默认地址时才填写。</div></div>
  <label class="full-row">自定义异步通知地址 notify_url<input class="input" name="notify_url" value="<?= htmlspecialchars($cfg['notify_url']??'') ?>" placeholder="通常留空，默认使用上方地址"></label>
  <label class="full-row">同步返回地址 return_url<input class="input" name="return_url" value="<?= htmlspecialchars($cfg['return_url']??'') ?>" placeholder="留空时使用 <?= htmlspecialchars($returnUrl ?? '') ?>"></label>
  <label class="full-row">应用私钥<textarea class="textarea" name="app_private_key" rows="4"><?= htmlspecialchars($cfg['app_private_key']??'') ?></textarea></label>
  <label class="full-row">支付宝公钥<textarea class="textarea" name="alipay_public_key" rows="4"><?= htmlspecialchars($cfg['alipay_public_key']??'') ?></textarea></label>
  <div class="mini full-row">支付宝官方支付必填：AppID、应用私钥、支付宝公钥、签名方式、notify_url/return_url。电脑网站支付与当面付产品码不同。</div>
<?php elseif($code==='alipay_qrcode'): ?>
  <label>应用 AppID<input class="input" name="app_id" value="<?= htmlspecialchars($cfg['app_id']??'') ?>"></label>
  <label>签名方式<select class="select" name="sign_type"><option value="RSA2" <?= (($cfg['sign_type']??'RSA2')==='RSA2')?'selected':'' ?>>RSA2</option><option value="RSA" <?= (($cfg['sign_type']??'')==='RSA')?'selected':'' ?>>RSA</option></select></label>
  <label>接口网关<input class="input" name="gateway" value="<?= htmlspecialchars($cfg['gateway']??'https://openapi.alipay.com/gateway.do') ?>"></label>
  <div class="callback-box"><strong>支付宝当面付异步通知回调地址</strong><div class="copy-line"><input class="input" readonly value="<?= htmlspecialchars($callbackUrls[$code] ?? '') ?>"><button type="button" class="btn btn-light js-copy-pay-url">复制</button></div><div class="callback-tip">这是支付结果异步通知地址，系统下单时也会自动作为 notify_url 传给支付宝；如支付宝开放平台/产品配置要求填写通知地址，也填这一条。它不是网页授权 OAuth 的“授权回调地址”。下方 notify_url 一般留空，只有需要覆盖默认地址时才填写。</div></div>
  <label class="full-row">自定义异步通知地址 notify_url<input class="input" name="notify_url" value="<?= htmlspecialchars($cfg['notify_url']??'') ?>" placeholder="通常留空，默认使用上方地址"></label>
  <label class="full-row">应用私钥<textarea class="textarea" name="app_private_key" rows="4"><?= htmlspecialchars($cfg['app_private_key']??'') ?></textarea></label>
  <label class="full-row">支付宝公钥<textarea class="textarea" name="alipay_public_key" rows="4"><?= htmlspecialchars($cfg['alipay_public_key']??'') ?></textarea></label>
  <div class="mini full-row">支付宝码支付按支付宝开放平台“当面付”接入：系统调用 alipay.trade.precreate 生成本次订单二维码链接，用户扫码后由支付宝异步通知自动入账。</div>
<?php else: ?>
  <label>易支付商户 PID<input class="input" name="pid" value="<?= htmlspecialchars($cfg['pid']??($cfg['merchant_id']??'')) ?>"></label>
  <label>商户密钥 Key<input class="input" type="password" name="api_key" value="<?= htmlspecialchars($cfg['api_key']??'') ?>"></label>
  <label>网关地址<input class="input" name="gateway" value="<?= htmlspecialchars($cfg['gateway']??'') ?>" placeholder="https://pay.example.com"></label>
  <label>支付类型<select class="select" name="pay_type"><option value="alipay" <?= (($cfg['pay_type']??'alipay')==='alipay')?'selected':'' ?>>支付宝</option><option value="wxpay" <?= (($cfg['pay_type']??'')==='wxpay')?'selected':'' ?>>微信</option><option value="qqpay" <?= (($cfg['pay_type']??'')==='qqpay')?'selected':'' ?>>QQ钱包</option></select></label>
  <div class="callback-box"><strong>易支付异步通知地址</strong><div class="copy-line"><input class="input" readonly value="<?= htmlspecialchars($callbackUrls[$code] ?? '') ?>"><button type="button" class="btn btn-light js-copy-pay-url">复制</button></div><div class="callback-tip">请填写到易支付商户后台的 notify_url / 异步通知地址。下方 notify_url 一般留空；只有需要覆盖默认地址时才填写。</div></div>
  <label class="full-row">自定义异步通知地址 notify_url<input class="input" name="notify_url" value="<?= htmlspecialchars($cfg['notify_url']??'') ?>" placeholder="通常留空，默认使用上方地址"></label>
  <label class="full-row">同步返回地址 return_url<input class="input" name="return_url" value="<?= htmlspecialchars($cfg['return_url']??'') ?>" placeholder="留空时使用 <?= htmlspecialchars($returnUrl ?? '') ?>"></label>
  <div class="mini full-row">易支付常见必填：PID、Key、网关地址、支付类型、notify_url、return_url。系统按 MD5 规则生成 sign。</div>
<?php endif; ?>
<?php if($canChannel): ?><button class="btn">保存该支付方式</button><?php endif; ?></form></section><?php endforeach; ?>
<?php elseif($tab==='packages'): ?><section class="pay-card"><h3>新增充值比例</h3><form method="post" action="/admin.php?path=payments/package" class="pay-grid"><?= csrf_field() ?><input class="input" name="title" placeholder="标题，如 10金币"><select class="select" name="currency_code"><?php foreach($currencies as $c): ?><option value="<?= htmlspecialchars($c['code']) ?>"><?= htmlspecialchars($c['name']) ?></option><?php endforeach; ?></select><input class="input" type="number" step="0.000001" name="amount" placeholder="到账数量"><input class="input" type="number" step="0.01" name="pay_amount" placeholder="支付金额元"><select class="select" name="status"><option value="active">启用</option><option value="inactive">关闭</option></select><input class="input" type="number" name="sort_order" value="0"><button class="btn">新增</button></form></section><div class="table-responsive"><table class="table"><thead><tr><th>ID</th><th>货币</th><th>到账</th><th>支付</th><th>状态</th><th>排序</th><th>操作</th></tr></thead><tbody><?php foreach($packages as $p): ?><tr><form method="post" action="/admin.php?path=payments/package"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$p['id'] ?>"><td>#<?= (int)$p['id'] ?></td><td><select class="select" name="currency_code"><?php foreach($currencies as $c): ?><option value="<?= htmlspecialchars($c['code']) ?>" <?= $c['code']===$p['currency_code']?'selected':'' ?>><?= htmlspecialchars($c['name']) ?></option><?php endforeach; ?></select><input class="input" name="title" value="<?= htmlspecialchars($p['title']) ?>"></td><td><input class="input" name="amount" value="<?= htmlspecialchars($p['amount']) ?>"></td><td><input class="input" name="pay_amount" value="<?= htmlspecialchars($p['pay_amount']) ?>"></td><td><select class="select" name="status"><option value="active" <?= $p['status']==='active'?'selected':'' ?>>启用</option><option value="inactive" <?= $p['status']!=='active'?'selected':'' ?>>关闭</option></select></td><td><input class="input" name="sort_order" value="<?= (int)$p['sort_order'] ?>"></td><td><button class="btn btn-light">保存</button></form><form method="post" action="/admin.php?path=payments/package/delete" onsubmit="return confirm('确认删除？')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$p['id'] ?>"><button class="btn btn-light admin-danger">删除</button></form></td></tr><?php endforeach; ?></tbody></table></div>
<?php elseif($tab==='orders'): ?><div class="table-responsive"><table class="table"><thead><tr><th>订单</th><th>用户</th><th>充值</th><th>支付</th><th>渠道</th><th>状态</th><th>时间</th><th>操作</th></tr></thead><tbody><?php foreach($orders as $o): ?><tr><td><?= htmlspecialchars($o['order_no']) ?></td><td><?= htmlspecialchars($o['nickname'] ?: $o['username']) ?></td><td><?= htmlspecialchars($o['amount']) ?> <?= htmlspecialchars($o['currency_name'] ?: currency_name_by_code((string)$o['currency_code'])) ?></td><td><?= htmlspecialchars($o['pay_amount']) ?> 元</td><td><?= htmlspecialchars($channelNames[$o['channel']] ?? $o['channel']) ?></td><td><span class="pay-status <?= htmlspecialchars($o['status']) ?>"><?= htmlspecialchars($o['status']) ?></span></td><td><?= htmlspecialchars($o['created_at']) ?></td><td><div class="admin-inline-actions"><?php if($o['status']==='pending' && $canManualPaid): ?><form method="post" action="/admin.php?path=payments/order/paid" onsubmit="var v=prompt('手动入账会直接增加用户余额。请输入 PAID 确认'); if(v!=='PAID') return false; this.querySelector('[name=confirm_text]').value=v; return true;"><?= csrf_field() ?><input type="hidden" name="order_no" value="<?= htmlspecialchars($o['order_no']) ?>"><input type="hidden" name="confirm_text" value=""><button class="btn btn-light">确认到账</button></form><?php endif; ?><?php if($canDeleteOrder): ?><form method="post" action="/admin.php?path=payments/order/delete" onsubmit="return confirm('确认删除该订单？删除后用户前台订单列表也会同步消失。已支付订单不会自动扣回已到账货币。')"><?= csrf_field() ?><input type="hidden" name="order_no" value="<?= htmlspecialchars($o['order_no']) ?>"><button class="btn btn-light admin-danger">删除</button></form><?php endif; ?></div></td></tr><?php endforeach; ?></tbody></table></div>
<?php elseif($tab==='redeem'): ?><section class="pay-card"><h3>生成兑换码</h3><form method="post" action="/admin.php?path=payments/redeem" class="pay-grid"><?= csrf_field() ?><input class="input" name="code" placeholder="留空自动生成"><select class="select" name="currency_code"><?php foreach($currencies as $c): ?><option value="<?= htmlspecialchars($c['code']) ?>"><?= htmlspecialchars($c['name']) ?></option><?php endforeach; ?></select><input class="input" name="amount" placeholder="兑换数量"><input class="input" type="number" name="max_uses" value="1"><input class="input" type="datetime-local" name="expires_at"><select class="select" name="status"><option value="active">启用</option><option value="inactive">关闭</option></select><button class="btn">生成</button></form></section><div class="table-responsive"><table class="table"><thead><tr><th>兑换码</th><th>货币</th><th>数量</th><th>使用</th><th>状态</th><th>过期</th><th>操作</th></tr></thead><tbody><?php foreach($codes as $c): ?><tr><td><strong><?= htmlspecialchars($c['code']) ?></strong></td><td><?= htmlspecialchars(currency_name_by_code($c['currency_code'])) ?></td><td><?= htmlspecialchars($c['amount']) ?></td><td><?= (int)$c['used_count'] ?>/<?= (int)$c['max_uses'] ?></td><td><?= htmlspecialchars($c['status']) ?></td><td><?= htmlspecialchars((string)$c['expires_at']) ?></td><td><form method="post" action="/admin.php?path=payments/redeem/delete" onsubmit="return confirm('确认删除？')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$c['id'] ?>"><button class="btn btn-light admin-danger">删除</button></form></td></tr><?php endforeach; ?></tbody></table></div>
<?php else: ?><?php if(!$canLogs): ?><div class="alert err">你没有查看回调日志的权限。</div><?php else: ?><div class="table-responsive"><table class="table"><thead><tr><th>ID</th><th>渠道</th><th>订单</th><th>状态</th><th>内容</th><th>时间</th></tr></thead><tbody><?php foreach($logs as $l): ?><tr><td>#<?= (int)$l['id'] ?></td><td><?= htmlspecialchars($l['channel']) ?></td><td><?= htmlspecialchars($l['order_no']) ?></td><td><?= htmlspecialchars($l['status']) ?></td><td><pre class="admin-pre-small"><?= htmlspecialchars($l['payload']) ?></pre></td><td><?= htmlspecialchars($l['created_at']) ?></td></tr><?php endforeach; ?></tbody></table></div><?php endif; ?><?php endif; ?>
<script>
document.querySelectorAll('.js-copy-pay-url').forEach(function(btn){
  btn.addEventListener('click', function(){
    var input = btn.closest('.copy-line')?.querySelector('input');
    if (!input) return;
    var text = input.value;
    if (navigator.clipboard && window.isSecureContext) {
      navigator.clipboard.writeText(text).then(function(){ btn.textContent='已复制'; setTimeout(function(){btn.textContent='复制';}, 1200); });
    } else {
      input.focus(); input.select(); document.execCommand('copy'); btn.textContent='已复制'; setTimeout(function(){btn.textContent='复制';}, 1200);
    }
  });
});
</script>
<?php require dirname(__DIR__) . '/layouts/main_footer.php'; ?>
