<?php
$pageTitle='认证管理'; require dirname(__DIR__) . '/layouts/main.php';
$tab=$tab??'requests'; $types=$types??[]; $requests=$requests??[]; $activeUsers=$activeUsers??[]; $cooldownUsers=$cooldownUsers??[]; $status=(string)($_GET['status']??''); $cooldownHours=(int)($cooldownHours??72);
$flashError=(string)($_SESSION['flash_error']??''); unset($_SESSION['flash_error']);
$flashSuccess=(string)($_SESSION['flash_success']??''); unset($_SESSION['flash_success']);
function verify_v_html(string $color): string { return '<span class="verify-v admin-dynamic-var" style="--v-color:'.htmlspecialchars($color, ENT_QUOTES).'">V</span>'; }
function admin_verify_remaining(int $seconds): string { $seconds=max(0,$seconds); $d=intdiv($seconds,86400); $seconds%=86400; $h=intdiv($seconds,3600); $seconds%=3600; $m=intdiv($seconds,60); if($d>0)return $d.'天'.$h.'小时'; if($h>0)return $h.'小时'.$m.'分钟'; return max(1,$m).'分钟'; }
?>

<div class="page-header"><div><div class="page-title">认证管理</div><div class="admin-muted admin-mt-4">管理认证申请、认证类型、已认证用户和重新认证冷却。</div></div></div>
<?php if($flashSuccess): ?><div class="verify-alert ok"><?= htmlspecialchars($flashSuccess) ?></div><?php endif; ?><?php if($flashError): ?><div class="verify-alert err"><?= htmlspecialchars($flashError) ?></div><?php endif; ?>
<div class="verify-tabs"><a class="<?= $tab==='requests'?'active':'' ?>" href="/admin.php?path=verifications&tab=requests">认证审核</a><a class="<?= $tab==='types'?'active':'' ?>" href="/admin.php?path=verifications&tab=types">认证类型</a><a class="<?= $tab==='users'?'active':'' ?>" href="/admin.php?path=verifications&tab=users">已认证用户</a><a class="<?= $tab==='cooldown'?'active':'' ?>" href="/admin.php?path=verifications&tab=cooldown">冷却管理</a></div>
<?php if ($tab==='types'): ?>
<div class="verify-card"><h3>新增认证类型</h3><form method="post" action="/admin.php?path=verifications/type" data-no-ajax class="admin-form-grid"><?= csrf_field() ?><input class="input" name="name" placeholder="认证名称，如 官方认证" required><input class="input" type="color" name="color" value="#2563eb" title="V标颜色"><input class="input" name="description" placeholder="认证说明（前台点击认证名展示）" required><input class="input" name="apply_note" placeholder="申请提示/条件"><select class="select" name="status"><option value="active">启用</option><option value="inactive">停用</option></select><label class="admin-muted"><input type="checkbox" name="allow_apply" value="1" checked> 允许用户申请</label><input class="input" type="number" name="sort_order" value="0"><button class="btn" type="submit">新增类型</button></form></div>
<div class="table-responsive"><table class="table"><thead><tr><th>V标</th><th>名称</th><th>说明</th><th>申请提示</th><th>状态</th><th>开放申请</th><th>排序</th><th>操作</th></tr></thead><tbody><?php foreach($types as $t): ?><tr><form method="post" action="/admin.php?path=verifications/type" data-no-ajax><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$t['id'] ?>"><td><?= verify_v_html((string)$t['color']) ?><div class="mini-note"><input class="input" type="color" name="color" value="<?= htmlspecialchars($t['color']) ?>"></div></td><td><input class="input" name="name" value="<?= htmlspecialchars($t['name']) ?>"></td><td><input class="input" name="description" value="<?= htmlspecialchars((string)$t['description']) ?>" required></td><td><input class="input" name="apply_note" value="<?= htmlspecialchars((string)$t['apply_note']) ?>"></td><td><select class="select" name="status"><option value="active" <?= $t['status']==='active'?'selected':'' ?>>启用</option><option value="inactive" <?= $t['status']!=='active'?'selected':'' ?>>停用</option></select></td><td><label><input type="checkbox" name="allow_apply" value="1" <?= !empty($t['allow_apply'])?'checked':'' ?>> 开放</label></td><td><input class="input" type="number" name="sort_order" value="<?= (int)$t['sort_order'] ?>"></td><td class="verify-actions"><button class="btn btn-light" type="submit">保存</button></form><form method="post" action="/admin.php?path=verifications/type/delete" data-no-ajax onsubmit="return confirm('确认删除该认证类型？已有用户使用时不会删除。')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$t['id'] ?>"><button class="btn btn-light admin-danger" type="submit">删除</button></form></td></tr><?php endforeach; ?></tbody></table></div>
<?php elseif ($tab==='users'): ?>
<div class="table-responsive"><table class="table"><thead><tr><th>用户</th><th>认证</th><th>通过时间</th><th>审核人</th><th>操作</th></tr></thead><tbody><?php foreach($activeUsers as $u): ?><tr><td><?= user_avatar_html($u, 'user-avatar', 34) ?> <?= htmlspecialchars($u['nickname'] ?: $u['username']) ?><div class="mini-note">UID <?= (int)$u['user_id'] ?></div></td><td><?= verify_v_html((string)$u['verification_color']) ?> <?= htmlspecialchars($u['verification_name']) ?><div class="mini-note"><?= htmlspecialchars((string)($u['verification_description'] ?? '')) ?></div></td><td><?= htmlspecialchars((string)$u['verified_at']) ?></td><td><?= htmlspecialchars((string)($u['verified_by_name'] ?? '')) ?></td><td><form method="post" action="/admin.php?path=verifications/revoke" data-no-ajax class="verify-actions" onsubmit="return confirm('确认撤销该用户认证？撤销后会进入重新认证冷却。')"><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$u['id'] ?>"><input class="input" name="reason" placeholder="撤销原因"><button class="btn btn-light admin-danger" type="submit">撤销</button></form></td></tr><?php endforeach; ?><?php if(empty($activeUsers)): ?><tr><td colspan="5" class="admin-empty">暂无已认证用户</td></tr><?php endif; ?></tbody></table></div>
<?php elseif ($tab==='cooldown'): ?>
<div class="verify-card"><h3>重新认证冷却时间</h3><form method="post" action="/admin.php?path=verifications/settings" data-no-ajax class="settings-row"><?= csrf_field() ?><label>撤销后冷却小时数<input class="input" type="number" min="0" max="8760" name="verification_reapply_cooldown_hours" value="<?= (int)$cooldownHours ?>"></label><button class="btn" type="submit">保存设置</button><span class="mini-note">0 表示不限制；默认建议 72 小时。</span></form></div>
<div class="table-responsive"><table class="table"><thead><tr><th>用户</th><th>原认证</th><th>撤销时间</th><th>冷却倒计时</th><th>可重新申请时间</th><th>原因</th></tr></thead><tbody><?php foreach($cooldownUsers as $u): ?><tr><td><?= user_avatar_html($u, 'user-avatar', 34) ?> <?= htmlspecialchars($u['nickname'] ?: $u['username']) ?><div class="mini-note">UID <?= (int)$u['user_id'] ?></div></td><td><?= verify_v_html((string)$u['verification_color']) ?> <?= htmlspecialchars($u['verification_name']) ?><div class="mini-note"><?= htmlspecialchars((string)($u['verification_description'] ?? '')) ?></div></td><td><?= htmlspecialchars((string)$u['revoked_at']) ?></td><td><span class="cooldown-pill" data-cooldown-seconds="<?= max(0,(int)($u['remaining_seconds'] ?? 0)) ?>"><?= htmlspecialchars(admin_verify_remaining((int)($u['remaining_seconds'] ?? 0))) ?></span></td><td><?= htmlspecialchars((string)($u['cooldown_until'] ?? '')) ?></td><td><?= htmlspecialchars((string)($u['revoke_reason'] ?? '')) ?></td></tr><?php endforeach; ?><?php if(empty($cooldownUsers)): ?><tr><td colspan="6" class="admin-empty">暂无冷却中的用户</td></tr><?php endif; ?></tbody></table></div>
<?php else: ?>
<form class="verify-filter" method="get" action="/admin.php"><input type="hidden" name="path" value="verifications"><input type="hidden" name="tab" value="requests"><select class="select" name="status"><option value="">全部状态</option><option value="pending" <?= $status==='pending'?'selected':'' ?>>待审核</option><option value="approved" <?= $status==='approved'?'selected':'' ?>>已通过</option><option value="rejected" <?= $status==='rejected'?'selected':'' ?>>已驳回</option></select><button class="btn">筛选</button><a class="btn btn-light admin-link-clean" href="/admin.php?path=verifications&tab=requests">清除</a></form>
<div class="table-responsive"><table class="table"><thead><tr><th>ID</th><th>用户</th><th>申请类型</th><th>申请资料</th><th>状态</th><th>时间</th><th>审核</th></tr></thead><tbody><?php foreach($requests as $r): ?><tr><td>#<?= (int)$r['id'] ?></td><td><?= user_avatar_html($r, 'user-avatar', 34) ?> <?= htmlspecialchars($r['nickname'] ?: $r['username']) ?><div class="mini-note">UID <?= (int)$r['user_id'] ?><?php if(!empty($r['real_name'])): ?> · <?= htmlspecialchars($r['real_name']) ?><?php endif; ?></div></td><td><?= verify_v_html((string)$r['verification_color']) ?> <?= htmlspecialchars($r['verification_name']) ?><div class="mini-note">类型：<?= htmlspecialchars((string)($r['type_name'] ?? $r['verification_name'])) ?></div></td><td class="admin-table-title"><div><?= nl2br(htmlspecialchars((string)$r['material'])) ?></div><?php if(!empty($r['review_note'])): ?><div class="mini-note">审核备注：<?= htmlspecialchars((string)$r['review_note']) ?></div><?php endif; ?></td><td><span class="status-pill status-<?= htmlspecialchars($r['status']) ?>"><?= ['pending'=>'待审核','approved'=>'已通过','rejected'=>'已驳回','cancelled'=>'已取消'][$r['status']] ?? $r['status'] ?></span></td><td><?= htmlspecialchars((string)$r['created_at']) ?></td><td><?php if($r['status']==='pending'): ?><div class="verify-actions"><form method="post" action="/admin.php?path=verifications/review" data-no-ajax><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input type="hidden" name="action" value="approve"><input class="input" name="note" placeholder="审核备注"><button class="btn" type="submit">通过</button></form><form method="post" action="/admin.php?path=verifications/review" data-no-ajax><?= csrf_field() ?><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><input type="hidden" name="action" value="reject"><input class="input" name="note" placeholder="驳回原因"><button class="btn btn-light admin-danger" type="submit">驳回</button></form></div><?php else: ?><span class="mini-note">已处理<?php if(!empty($r['reviewer_name'])): ?> · <?= htmlspecialchars($r['reviewer_name']) ?><?php endif; ?></span><?php endif; ?></td></tr><?php endforeach; ?><?php if(empty($requests)): ?><tr><td colspan="7" class="admin-empty">暂无认证申请</td></tr><?php endif; ?></tbody></table></div>
<?php endif; ?>
<script>(function(){function fmt(n){n=Math.max(0,n);var d=Math.floor(n/86400);n%=86400;var h=Math.floor(n/3600);n%=3600;var m=Math.floor(n/60);if(d>0)return d+'天'+h+'小时';if(h>0)return h+'小时'+m+'分钟';return Math.max(1,m)+'分钟';}var els=[].slice.call(document.querySelectorAll('[data-cooldown-seconds]'));if(!els.length)return;setInterval(function(){els.forEach(function(el){var s=parseInt(el.dataset.cooldownSeconds||'0',10)-1;el.dataset.cooldownSeconds=String(s);el.textContent=s>0?fmt(s):'已结束';});},1000);})();</script>
<?php require dirname(__DIR__) . '/layouts/main_footer.php'; ?>
